paths:
  flamsteed: "flamsteed/lib/javascripts/flamsteed"
  hogan: "hogan/dist/hogan-3.0.0.amd"
  jplugs: "jquery-plugins"
  jquery: "jquery/dist/jquery"
  usabilla: "usabilla/usabilla"

modules:
  - name: 'infobox'
  - name: 'app_core_external'
  - name: 'app_core'
    exclude:
      - 'infobox'
  - name: 'app_core_legacy'
    exclude:
      - 'infobox'
  - name: 'styleguide'
    exclude:
      - 'infobox'

findNestedDependencies: true
